---
name: publish

on: [push]

jobs:
  publish-hello-world-image:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build the hello-world Docker image
      run: |
        docker build .  --tag ghcr.io/timberhill/hello-github-artefacts:0.1.1 --tag ghcr.io/timberhill/hello-github-artefacts:latest
        docker push ghcr.io/timberhill/hello-github-artefacts:0.1.1
        docker push ghcr.io/timberhill/hello-github-artefacts:latest
