---
name: publish-image

on:
  push:
    branches:
      - main
    paths:
      - "docker/*"

jobs:
  publish-hello-world-image:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build the hello-world Docker image
      working-directory: ./docker
      run: |
        export VERSION=$(awk '/appVersion:/ {print $2}' ../Chart.yaml | tr -d '"')
        docker build . --tag ghcr.io/timberhill/hello-github-artefacts:${VERSION} --tag ghcr.io/timberhill/hello-github-artefacts:latest
        docker push ghcr.io/timberhill/hello-github-artefacts:${VERSION}
        docker push ghcr.io/timberhill/hello-github-artefacts:latest
